# pytest.ini or .pytest.ini
[pytest]
minversion = 6.0
addopts = --html=./reports/report.html
    --self-contained-html
    -v
    -s
    --browser firefox
    gi--browser chromium
    --headed

testpaths =
    tests
    integration

markers =
    smoke: szybkie testy krytyczne (poniżej 5s)
    regression: pełne testy regresji (stabilność)
    critical: ścieżki biznesowo krytyczne
    slow: testy dłuższe niż 30s
    api: testy API (mockowane)
    ui: testy UI (Playwright)